version: 1.0.{build}

platform: Any CPU

configuration: Release

environment:
  xmlDocs_solution: XmlDocToMarkdown/XmlDocToMarkdown.sln
  oauth_access_token:
    secure: CtV9XcQ8dUwJoI5XvZS21wl/S72lgnBB0k1eK5GAjseS6Z33uuvLALxVFAq6IqLT

build_script:
 - msbuild %xmlDocs_solution%
  
  
on_success:    
     Get-ChildItem env:  
     - git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR 
     - git config --global credential.helper store      
     - git clone https://%oauth_access_token%@github.com/DynamoDS/DynamoAPI.git
test: off 
