version: 1.0.{build}

platform: Any CPU

configuration: Release

environment:
  xmlDocs_solution: XmlDocToMarkdown/XmlDocToMarkdown.sln
  access_token:
    secure:CtV9XcQ8dUwJoI5XvZS21wl/S72lgnBB0k1eK5GAjseS6Z33uuvLALxVFAq6IqLT
build_script:
  - msbuild %xmlDocs_solution%


on_success:  
 - ps: >- 
    if($env:APPVEYOR_PULL_REQUEST_NUMBER -eq ' ') {	
      git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n" 
      git clone https://DynamoDS:$($env:access_token)@github.com/DynamoDS/DynamoAPI.git
    }  
   -ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER
  
test: off