version: 1.0.{build}

platform: Any CPU

configuration: Release

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  xmlDocs_solution: XmlDocToMarkdown/XmlDocToMarkdown.sln
  oauth_access_token:
    secure: 9V2HPr20tWakE4vLSsHHzE0UyGuU4UCKEbUwK4UJIlseBRuw+j5WBaEWQYXl+M8W

build_script:
 - msbuild %xmlDocs_solution%

on_success:
- ps: >- 
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {	
      git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
      git config --global credential.helper store    
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"   
      git clone -q https://$($env:oauth_access_token):x-oauth-basic@github.com/DynamoDS/DynamoAPI.git  c:\projects\xmlmarkdown\DynamoAPI 2>&1 | % { $_.ToString() }      
    }
  
test: off 
