site_name: Dynamo
repo_url: http://dynamods.github.io/DynamoAPI/
site_author: Dynamo
pages:
- Home: index.md
- API:
    - Dynamo:
      - 'CustomNodeDefinition' : 'Dynamo/CustomNodeDefinition.md'
      - 'CustomNodeInfo' : 'Dynamo/CustomNodeInfo.md'
      - 'DefaultRenderPackage' : 'Dynamo/DefaultRenderPackage.md'
      - 'DefaultRenderPackageFactory' : 'Dynamo/DefaultRenderPackageFactory.md'
      - 'DynamoLogger' : 'Dynamo/DynamoLogger.md'
      - 'LogEventArgs' : 'Dynamo/LogEventArgs.md'
      - 'LogEventHandler' : 'Dynamo/LogEventHandler.md'
      - 'LogLevel' : 'Dynamo/LogLevel.md'
      - 'PreferenceSettings' : 'Dynamo/PreferenceSettings.md'
      - 'WarningLevel' : 'Dynamo/WarningLevel.md'
    - Dynamo.Annotations:
      - 'NotifyPropertyChangedInvocatorAttribute' : 'Dynamo_Annotations/NotifyPropertyChangedInvocatorAttribute.md'
    - Dynamo.Core:
      - 'AuthenticationManager' : 'Dynamo_Core/AuthenticationManager.md'
      - 'Context' : 'Dynamo_Core/Context.md'
      - 'CrashPromptArgs' : 'Dynamo_Core/CrashPromptArgs.md'
      - 'CustomNodeManager' : 'Dynamo_Core/CustomNodeManager.md'
      - 'DebugSettings' : 'Dynamo_Core/DebugSettings.md'
      - 'IUndoRedoRecorderClient' : 'Dynamo_Core/IUndoRedoRecorderClient.md'
      - 'NodeGraph' : 'Dynamo_Core/NodeGraph.md'
      - 'NotificationObject' : 'Dynamo_Core/NotificationObject.md'
    - Dynamo.Core.Threading:
      - 'AsyncTask' : 'Dynamo_Core_Threading/AsyncTask.md'
      - 'AsyncTaskCompletedHandler' : 'Dynamo_Core_Threading/AsyncTaskCompletedHandler.md'
      - 'DelegateBasedAsyncTask' : 'Dynamo_Core_Threading/DelegateBasedAsyncTask.md'
      - 'Disposable' : 'Dynamo_Core_Threading/Disposable.md'
      - 'DynamoScheduler' : 'Dynamo_Core_Threading/DynamoScheduler.md'
      - 'IScheduler' : 'Dynamo_Core_Threading/IScheduler.md'
      - 'TaskStateChangedEventArgs' : 'Dynamo_Core_Threading/TaskStateChangedEventArgs.md'
      - 'TaskStateChangedEventHandler' : 'Dynamo_Core_Threading/TaskStateChangedEventHandler.md'
      - 'TimeStamp' : 'Dynamo_Core_Threading/TimeStamp.md'
    - Dynamo.Engine:
      - 'AstBuilder' : 'Dynamo_Engine/AstBuilder.md'
      - 'AstBuiltEventHandler' : 'Dynamo_Engine/AstBuiltEventHandler.md'
      - 'CompilationServices' : 'Dynamo_Engine/CompilationServices.md'
      - 'EngineController' : 'Dynamo_Engine/EngineController.md'
      - 'FunctionDescriptor' : 'Dynamo_Engine/FunctionDescriptor.md'
      - 'FunctionDescriptorParams' : 'Dynamo_Engine/FunctionDescriptorParams.md'
      - 'FunctionGroup' : 'Dynamo_Engine/FunctionGroup.md'
      - 'FunctionType' : 'Dynamo_Engine/FunctionType.md'
      - 'IAstNodeContainer' : 'Dynamo_Engine/IAstNodeContainer.md'
      - 'IFunctionDescriptor' : 'Dynamo_Engine/IFunctionDescriptor.md'
      - 'ITraceReconciliationProcessor' : 'Dynamo_Engine/ITraceReconciliationProcessor.md'
      - 'LibraryServices' : 'Dynamo_Engine/LibraryServices.md'
      - 'LiveRunnerServices' : 'Dynamo_Engine/LiveRunnerServices.md'
      - 'TraceReconciliationEventArgs' : 'Dynamo_Engine/TraceReconciliationEventArgs.md'
      - 'XmlDocumentationExtensions' : 'Dynamo_Engine/XmlDocumentationExtensions.md'
    - Dynamo.Engine.NodeToCode:
      - 'INamingProvider' : 'Dynamo_Engine_NodeToCode/INamingProvider.md'
    - Dynamo.Extensions:
      - 'EnumDescription' : 'Dynamo_Extensions/EnumDescription.md'
      - 'EnumDescriptionAttribute' : 'Dynamo_Extensions/EnumDescriptionAttribute.md'
      - 'ExtensionDefinition' : 'Dynamo_Extensions/ExtensionDefinition.md'
      - 'ExtensionLibraryLoader' : 'Dynamo_Extensions/ExtensionLibraryLoader.md'
      - 'ExtensionLoader' : 'Dynamo_Extensions/ExtensionLoader.md'
      - 'ExtensionManager' : 'Dynamo_Extensions/ExtensionManager.md'
      - 'IExtension' : 'Dynamo_Extensions/IExtension.md'
      - 'IExtensionLoader' : 'Dynamo_Extensions/IExtensionLoader.md'
      - 'IExtensionManager' : 'Dynamo_Extensions/IExtensionManager.md'
      - 'ReadyParams' : 'Dynamo_Extensions/ReadyParams.md'
      - 'StartupParams' : 'Dynamo_Extensions/StartupParams.md'
    - Dynamo.Interfaces:
      - 'ICustomNodeManager' : 'Dynamo_Interfaces/ICustomNodeManager.md'
      - 'ICustomNodeSource' : 'Dynamo_Interfaces/ICustomNodeSource.md'
      - 'ICustomNodeWorkspaceModel' : 'Dynamo_Interfaces/ICustomNodeWorkspaceModel.md'
      - 'IDynamoModel' : 'Dynamo_Interfaces/IDynamoModel.md'
      - 'ILibraryLoader' : 'Dynamo_Interfaces/ILibraryLoader.md'
      - 'ILogger' : 'Dynamo_Interfaces/ILogger.md'
      - 'ILogMessage' : 'Dynamo_Interfaces/ILogMessage.md'
      - 'ILogSource' : 'Dynamo_Interfaces/ILogSource.md'
      - 'IPathManager' : 'Dynamo_Interfaces/IPathManager.md'
      - 'IPathResolver' : 'Dynamo_Interfaces/IPathResolver.md'
      - 'IPreferences' : 'Dynamo_Interfaces/IPreferences.md'
      - 'IRenderPackageFactory' : 'Dynamo_Interfaces/IRenderPackageFactory.md'
      - 'IRenderPackageSource' : 'Dynamo_Interfaces/IRenderPackageSource.md'
      - 'ISchedulerThread' : 'Dynamo_Interfaces/ISchedulerThread.md'
      - 'ISource' : 'Dynamo_Interfaces/ISource.md'
      - 'IWorkspaceModel' : 'Dynamo_Interfaces/IWorkspaceModel.md'
    - Dynamo.Library:
      - 'TypedParameter' : 'Dynamo_Library/TypedParameter.md'
    - Dynamo.Logging:
      - 'LogMessage' : 'Dynamo_Logging/LogMessage.md'
      - 'LogSourceBase' : 'Dynamo_Logging/LogSourceBase.md'
    - Dynamo.Migration:
      - 'MigrationManager' : 'Dynamo_Migration/MigrationManager.md'
      - 'NodeMigrationAttribute' : 'Dynamo_Migration/NodeMigrationAttribute.md'
      - 'NodeMigrationData' : 'Dynamo_Migration/NodeMigrationData.md'
      - 'PortId' : 'Dynamo_Migration/PortId.md'
      - 'WorkspaceMigrationAttribute' : 'Dynamo_Migration/WorkspaceMigrationAttribute.md'
      - 'WorkspaceMigrations' : 'Dynamo_Migration/WorkspaceMigrations.md'
    - Dynamo.Models:
      - 'ActionHandler' : 'Dynamo_Models/ActionHandler.md'
      - 'AnnotationModel' : 'Dynamo_Models/AnnotationModel.md'
      - 'ConnectorModel' : 'Dynamo_Models/ConnectorModel.md'
      - 'ConnectorType' : 'Dynamo_Models/ConnectorType.md'
      - 'CustomNodeWorkspaceModel' : 'Dynamo_Models/CustomNodeWorkspaceModel.md'
      - 'DynamoModel' : 'Dynamo_Models/DynamoModel.md'
      - 'DynamoModelHandler' : 'Dynamo_Models/DynamoModelHandler.md'
      - 'ElementState' : 'Dynamo_Models/ElementState.md'
      - 'EvaluationCompletedEventArgs' : 'Dynamo_Models/EvaluationCompletedEventArgs.md'
      - 'HomeWorkspaceModel' : 'Dynamo_Models/HomeWorkspaceModel.md'
      - 'IEngineControllerManager' : 'Dynamo_Models/IEngineControllerManager.md'
      - 'ILocatable' : 'Dynamo_Models/ILocatable.md'
      - 'INodeFactory' : 'Dynamo_Models/INodeFactory.md'
      - 'INodeLoader' : 'Dynamo_Models/INodeLoader.md'
      - 'LacingStrategy' : 'Dynamo_Models/LacingStrategy.md'
      - 'ModelBase' : 'Dynamo_Models/ModelBase.md'
      - 'NodeEventHandler' : 'Dynamo_Models/NodeEventHandler.md'
      - 'NodeFactory' : 'Dynamo_Models/NodeFactory.md'
      - 'NodeHandler' : 'Dynamo_Models/NodeHandler.md'
      - 'NodeModel' : 'Dynamo_Models/NodeModel.md'
      - 'NodeModelAssemblyLoader' : 'Dynamo_Models/NodeModelAssemblyLoader.md'
      - 'NodeModelExtensions' : 'Dynamo_Models/NodeModelExtensions.md'
      - 'NoteModel' : 'Dynamo_Models/NoteModel.md'
      - 'PortData' : 'Dynamo_Models/PortData.md'
      - 'PortEventType' : 'Dynamo_Models/PortEventType.md'
      - 'PortModel' : 'Dynamo_Models/PortModel.md'
      - 'PortPosition' : 'Dynamo_Models/PortPosition.md'
      - 'PortsChangedHandler' : 'Dynamo_Models/PortsChangedHandler.md'
      - 'PortType' : 'Dynamo_Models/PortType.md'
      - 'PresetModel' : 'Dynamo_Models/PresetModel.md'
      - 'RunSettings' : 'Dynamo_Models/RunSettings.md'
      - 'RunType' : 'Dynamo_Models/RunType.md'
      - 'SaveContext' : 'Dynamo_Models/SaveContext.md'
      - 'ScopedNodeModel' : 'Dynamo_Models/ScopedNodeModel.md'
      - 'SnapExtensionEdges' : 'Dynamo_Models/SnapExtensionEdges.md'
      - 'TypeLoadData' : 'Dynamo_Models/TypeLoadData.md'
      - 'UIDispatcherEventArgs' : 'Dynamo_Models/UIDispatcherEventArgs.md'
      - 'UpdateValueParams' : 'Dynamo_Models/UpdateValueParams.md'
      - 'WorkspaceHandler' : 'Dynamo_Models/WorkspaceHandler.md'
      - 'WorkspaceInfo' : 'Dynamo_Models/WorkspaceInfo.md'
      - 'WorkspaceModel' : 'Dynamo_Models/WorkspaceModel.md'
    - Dynamo.Nodes:
      - 'AlsoKnownAsAttribute' : 'Dynamo_Nodes/AlsoKnownAsAttribute.md'
      - 'BuiltinNodeCategories' : 'Dynamo_Nodes/BuiltinNodeCategories.md'
      - 'CodeBlockNodeModel' : 'Dynamo_Nodes/CodeBlockNodeModel.md'
      - 'CodeBlockUtils' : 'Dynamo_Nodes/CodeBlockUtils.md'
      - 'CustomNodeController' : 'Dynamo_Nodes/CustomNodeController.md'
      - 'DoNotLoadOnPlatformsAttribute' : 'Dynamo_Nodes/DoNotLoadOnPlatformsAttribute.md'
      - 'DSFunction' : 'Dynamo_Nodes/DSFunction.md'
      - 'DSFunctionBase' : 'Dynamo_Nodes/DSFunctionBase.md'
      - 'DSVarArgFunction' : 'Dynamo_Nodes/DSVarArgFunction.md'
      - 'DummyNode' : 'Dynamo_Nodes/DummyNode.md'
      - 'Function' : 'Dynamo_Nodes/Function.md'
      - 'FunctionCallBase' : 'Dynamo_Nodes/FunctionCallBase.md'
      - 'FunctionCallNodeController' : 'Dynamo_Nodes/FunctionCallNodeController.md'
      - 'IsDesignScriptCompatibleAttribute' : 'Dynamo_Nodes/IsDesignScriptCompatibleAttribute.md'
      - 'IsInteractiveAttribute' : 'Dynamo_Nodes/IsInteractiveAttribute.md'
      - 'IsMetaNodeAttribute' : 'Dynamo_Nodes/IsMetaNodeAttribute.md'
      - 'NodeCategoryAttribute' : 'Dynamo_Nodes/NodeCategoryAttribute.md'
      - 'NodeDeprecatedAttribute' : 'Dynamo_Nodes/NodeDeprecatedAttribute.md'
      - 'NodeDescriptionAttribute' : 'Dynamo_Nodes/NodeDescriptionAttribute.md'
      - 'NodeNameAttribute' : 'Dynamo_Nodes/NodeNameAttribute.md'
      - 'NodeObsoleteAttribute' : 'Dynamo_Nodes/NodeObsoleteAttribute.md'
      - 'NodeSearchableAttribute' : 'Dynamo_Nodes/NodeSearchableAttribute.md'
      - 'NodeSearchTagsAttribute' : 'Dynamo_Nodes/NodeSearchTagsAttribute.md'
      - 'NodeTypeIdAttribute' : 'Dynamo_Nodes/NodeTypeIdAttribute.md'
      - 'NotSearchableInCustomNodeWorkspace' : 'Dynamo_Nodes/NotSearchableInCustomNodeWorkspace.md'
      - 'NotSearchableInHomeWorkspace' : 'Dynamo_Nodes/NotSearchableInHomeWorkspace.md'
      - 'Output' : 'Dynamo_Nodes/Output.md'
      - 'Statement' : 'Dynamo_Nodes/Statement.md'
      - 'Symbol' : 'Dynamo_Nodes/Symbol.md'
      - 'UnresolvedFunctionException' : 'Dynamo_Nodes/UnresolvedFunctionException.md'
      - 'Utilities' : 'Dynamo_Nodes/Utilities.md'
      - 'Variable' : 'Dynamo_Nodes/Variable.md'
      - 'VariableInputNode' : 'Dynamo_Nodes/VariableInputNode.md'
      - 'VariableInputNodeController' : 'Dynamo_Nodes/VariableInputNodeController.md'
      - 'ZeroTouchNodeController' : 'Dynamo_Nodes/ZeroTouchNodeController.md'
      - 'ZeroTouchVarArgNodeController' : 'Dynamo_Nodes/ZeroTouchVarArgNodeController.md'
    - Dynamo.Properties:
      - 'Resources' : 'Dynamo_Properties/Resources.md'
    - Dynamo.Search:
      - 'BrowserInternalElement' : 'Dynamo_Search/BrowserInternalElement.md'
      - 'BrowserItem' : 'Dynamo_Search/BrowserItem.md'
      - 'ElementTypes' : 'Dynamo_Search/ElementTypes.md'
      - 'NodeSearchModel' : 'Dynamo_Search/NodeSearchModel.md'
      - 'SearchCategoryUtil' : 'Dynamo_Search/SearchCategoryUtil.md'
      - 'SearchDictionary' : 'Dynamo_Search/SearchDictionary.md'
      - 'SearchElementGroup' : 'Dynamo_Search/SearchElementGroup.md'
      - 'SearchLibrary' : 'Dynamo_Search/SearchLibrary.md'
    - Dynamo.Search.Interfaces:
      - 'ISearchCategory' : 'Dynamo_Search_Interfaces/ISearchCategory.md'
      - 'ISearchEntry' : 'Dynamo_Search_Interfaces/ISearchEntry.md'
    - Dynamo.Search.SearchElements:
      - 'CodeBlockNodeSearchElement' : 'Dynamo_Search_SearchElements/CodeBlockNodeSearchElement.md'
      - 'CustomNodeSearchElement' : 'Dynamo_Search_SearchElements/CustomNodeSearchElement.md'
      - 'DragDropNodeSearchElementInfo' : 'Dynamo_Search_SearchElements/DragDropNodeSearchElementInfo.md'
      - 'NodeModelSearchElement' : 'Dynamo_Search_SearchElements/NodeModelSearchElement.md'
      - 'NodeModelSearchElementBase' : 'Dynamo_Search_SearchElements/NodeModelSearchElementBase.md'
      - 'NodeSearchElement' : 'Dynamo_Search_SearchElements/NodeSearchElement.md'
      - 'SearchElementBase' : 'Dynamo_Search_SearchElements/SearchElementBase.md'
      - 'ZeroTouchSearchElement' : 'Dynamo_Search_SearchElements/ZeroTouchSearchElement.md'
    - Dynamo.Selection:
      - 'ISelectable' : 'Dynamo_Selection/ISelectable.md'
    - Dynamo.UI:
      - 'Configurations' : 'Dynamo_UI/Configurations.md'
    - Dynamo.UpdateManager:
      - 'AppVersionInfo' : 'Dynamo_UpdateManager/AppVersionInfo.md'
      - 'BinaryVersion' : 'Dynamo_UpdateManager/BinaryVersion.md'
      - 'IAppVersionInfo' : 'Dynamo_UpdateManager/IAppVersionInfo.md'
      - 'IAsynchronousRequest' : 'Dynamo_UpdateManager/IAsynchronousRequest.md'
      - 'IDynamoLookUp' : 'Dynamo_UpdateManager/IDynamoLookUp.md'
      - 'IUpdateManager' : 'Dynamo_UpdateManager/IUpdateManager.md'
      - 'IUpdateManagerConfiguration' : 'Dynamo_UpdateManager/IUpdateManagerConfiguration.md'
      - 'ShutdownRequestedEventHandler' : 'Dynamo_UpdateManager/ShutdownRequestedEventHandler.md'
      - 'UpdateDownloadedEventArgs' : 'Dynamo_UpdateManager/UpdateDownloadedEventArgs.md'
      - 'UpdateDownloadedEventHandler' : 'Dynamo_UpdateManager/UpdateDownloadedEventHandler.md'
      - 'UpdateManagerConfiguration' : 'Dynamo_UpdateManager/UpdateManagerConfiguration.md'
theme_dir: Theme
